### ISSUE TITLE
Props not able to render from Home Page to Chat page

### ISSUE THREAD

**Issue by dhavaljardosh** [FaridSafi/ChatApp#5]
I am still at the login screen i.e adding Name and pressing Next. 
As soon as I press Next, I am supposed to get the `name` 

But instead I am getting `<Scene key="chat" component={Chat} title="Chat"/>` key value, i.e "chat"

Not sure what the problem is. Guess I am not using the constructor(props){super(props)} ??

**Comment by pttd1304** [comment]
Try using a different name for the param when passing the props. i.e Actions.chat({username: this.state.name}) (instead of 'name: this.state.name').

**Comment by dhavaljardosh** [comment]
Sure, I will try and let you know. Thank you 👍

**Comment by SelenaWong** [comment]
Thanks a lot .When I use a different name it works .
